#!/usr/bin/env bash
# Run Ralph v2 autonomous implementation loop
# Generated by /ralph-pipeline-full-auto on 2026-02-13
# PRD: tasks/prd-oss-prep-v2.md
# Stories: 12 stories across 3 epics
# Premortems: 2 passes completed (4 issues fixed in P1, 0 in P2)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# Preflight checks
command -v ralph >/dev/null 2>&1 || { echo "Error: ralph not found on PATH. Run install.sh first."; exit 1; }
[[ -f .ralph/stories.txt ]] || { echo "Error: .ralph/stories.txt not found."; exit 1; }
[[ -f .ralph/config.json ]] || { echo "Error: .ralph/config.json not found."; exit 1; }

# Count stories and batches
total_stories=$(grep -c '^[0-9]' .ralph/stories.txt || true)
total_batches=$(grep -c '^\# \[batch:' .ralph/stories.txt || true)

echo "Ralph v2 — Autonomous Implementation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Project: oss-prep v2 migration"
echo "Stories: ${total_stories}"
echo "Batches: ${total_batches}"
echo "Mode:    parallel (max 4 concurrent)"
echo ""
echo "Batch 1: Foundation (patterns + state schema)"
echo "Batch 2: Phase extraction (10 phases, parallel)"
echo "Batch 3: Orchestrator replacement"
echo ""
echo "Starting in 3 seconds... (Ctrl+C to cancel)"
sleep 3

# Run Ralph
ralph run --parallel --no-interactive "$@"
