#!/usr/bin/env bash
# Run Ralph v2 autonomous implementation loop for oss-prep skill
# Generated by /ralph-pipeline-full-auto on 2026-02-12
# PRD: tasks/prd-oss-prep.md
# Stories: 11 stories across 4 epics (11 sequential batches)
# Premortems: 2 passes completed

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# Preflight checks
[[ -f .ralph/stories.txt ]] || { echo "Error: .ralph/stories.txt not found."; exit 1; }

# Count stories and batches
total_stories=$(grep -c '^[0-9]' .ralph/stories.txt || true)
total_batches=$(grep -c '^\# \[batch:' .ralph/stories.txt || true)

echo "Ralph v2 — Autonomous Implementation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Project:  oss-prep (Open-Source Preparation Tool)"
echo "Target:   skills/oss-prep/SKILL.md"
echo "Stories:  ${total_stories}"
echo "Batches:  ${total_batches}"
echo "Mode:     sequential (single-file target)"
echo ""
echo "Story Plan (all sequential — single-file target):"
echo "   1.  1.1 SKILL.md Skeleton       7.  3.2 Phase 5: Documentation"
echo "   2.  1.2 Phase 0: Recon          8.  3.3 Phase 6: GitHub Setup"
echo "   3.  2.1 Phase 1: Secrets        9.  3.4 Phase 7: Naming/Identity"
echo "   4.  2.2 Phase 2: PII           10.  4.1 Phase 8: History Flatten"
echo "   5.  2.3 Phase 3: Deps          11.  4.2 Phase 9: Final Report"
echo "   6.  3.1 Phase 4: Code Quality"
echo ""
echo "Starting in 3 seconds... (Ctrl+C to cancel)"
sleep 3

# Process stories sequentially (single-file target requires sequential writes)
story_num=0
while IFS='|' read -r id title; do
    id=$(echo "$id" | xargs)
    title=$(echo "$title" | xargs)

    # Skip comments and empty lines
    [[ "$id" =~ ^#.*$ || -z "$id" ]] && continue

    story_num=$((story_num + 1))

    # Find the spec file
    epic="${id%%.*}"
    slug=$(find specs/epic-"$epic"/ -name "story-${id}-*.md" 2>/dev/null | head -1)

    if [[ -z "$slug" ]]; then
        echo "Warning: No spec found for story $id, skipping"
        continue
    fi

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "[$story_num/$total_stories] Story $id: $title"
    echo "Spec:  $slug"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    # Run Claude Code with the spec as context
    claude --print --dangerously-skip-permissions \
        "Implement the following Ralph v2 story spec for the oss-prep skill. Read the spec file at: $SCRIPT_DIR/$slug — then implement exactly what it describes. Write the specified section of skills/oss-prep/SKILL.md. If SKILL.md doesn't exist yet (story 1.1), create it. If it exists, add your phase section at the appropriate location after the existing content. Do NOT modify sections written by previous stories. After implementation, verify the section is complete by re-reading SKILL.md." \
        2>&1 || {
        echo "Error: Story $id failed. Check output above."
        echo "You can resume by prefixing completed stories with 'x' in .ralph/stories.txt"
        exit 1
    }

    # Commit after each story
    git add -A && git commit -m "ralph: implement story $id — $title" 2>/dev/null || true

    echo "Story $id complete. [$story_num/$total_stories]"
done < .ralph/stories.txt

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "All $total_stories stories implemented!"
echo "Review: skills/oss-prep/SKILL.md"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
